# Need to first provision a directory /mnt/disks/vmr on host node
#  use this for Solace message spool.  Used to test various fs and mount options
solace:
  redundancy: false
  size: prod1k
# Current options are [gcp|aws]
cloudProvider: SOLOS_CLOUD_PROVIDER
image:
  repository: SOLOS_IMAGE_REPO
  tag: SOLOS_IMAGE_TAG
  pullPolicy: IfNotPresent
filepaths:
  configmap: "/mnt/disks/solace"
  secrets: "/mnt/disks/secrets"
service:
  internal: false
  type: LoadBalancer
  externalPort:
    - port: 22
      protocol: TCP
      name: ssh
    - port: 8080
      protocol: TCP
      name: semp
    - port: 55555
      protocol: TCP
      name: smf
  internalPort:
    - port: 80
      protocol: TCP
    - port: 8080
      protocol: TCP
    - port: 443
      protocol: TCP
    - port: 8443
      protocol: TCP
    - port: 55555
      protocol: TCP
    - port: 22
storage:
  persistent: false
  hostPath: /mnt/disks/vmr
