# Create a PV of specified size and type, bind PVC to PV 
configurationFiles: false
solace:
  redundancy: false
  size: prod1k
# Current options are [gcp|aws]
cloudProvider: SOLOS_CLOUD_PROVIDER
image:
  repository: SOLOS_IMAGE_REPO
  tag: SOLOS_IMAGE_TAG
  pullPolicy: IfNotPresent
filepaths:
  configmap: "/mnt/disks/solace"
  secrets: "/mnt/disks/secrets"
service:
  internal: false
  type: LoadBalancer
  externalPort:
    - port: 22
      protocol: TCP
      name: ssh
      targetport: 2222
    - port: 8080
      protocol: TCP
      name: semp
    - port: 55555
      protocol: TCP
      name: smf
    - port: 55003
      protocol: TCP
      name: smfcompr
    - port: 55443
      protocol: TCP
      name: smftls
    - port: 943
      protocol: TCP
      name: semptls
      targetport: 60943
    - port: 80
      protocol: TCP
      name: web
      targetport: 60080
    - port: 443
      protocol: TCP
      name: webtls
      targetport: 60443
  internalPort:
    - port: 2222
      protocol: TCP
    - port: 8080
      protocol: TCP
    - port: 55555
      protocol: TCP
    - port: 55003
      protocol: TCP
    - port: 55443
      protocol: TCP
    - port: 60943
      protocol: TCP
    - port: 60080
      protocol: TCP
    - port: 60443
      protocol: TCP
storage:
  type: standard
  persistent: true
  size: 30Gi