# If there are configuration files load this part of the template
{{ if .Values.configurationFiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}
data:
  {{ range $path, $bytes := .Files.Glob "files/*" }}
  {{ $path | base }}: |
{{ $bytes | printf "%s" | indent 4}}
  {{ end }}
{{ end }}