apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "solace.fullname" . }}-postupgrade
  labels:
    app: {{ template "solace.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": "post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      labels:
        app: {{ template "solace.name" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
      - name: post-upgrade-job
        image: "alpine:latest"
        env:
        - name: STATEFULSET_NAME
          value: {{ template "solace.fullname" . }}
        - name: STATEFULSET_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: ["/bin/sh", "-c"]
        args: [ "apk add --no-cache bash; apk add --no-cache curl; apk add --no-cache libxml2-utils; {{ .Values.filepaths.configmap }}/post_vertical_scale_upgrade.sh -s {{ .Values.solace.size }} -r {{ .Release.Name }}" ]

        volumeMounts:
        - name: config-map
          mountPath: {{ .Values.filepaths.configmap }}
        - name: secrets
          mountPath: {{ .Values.filepaths.secrets }}
          readOnly: true

      volumes:
      - name: config-map
        configMap:
          name: {{ template "solace.fullname" . }}
          defaultMode: 0755
      - name: secrets
        secret:
          secretName: {{ template "solace.fullname" . }}-secrets
          defaultMode: 0400