---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "solace.fullname" . }}-secrets
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "solace.name" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "5"
type: Opaque
data:
  username_admin_password: {{ b64enc "SOLOS_ADMIN_PASSWORD" }}