---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "solace.fullname" . }}-secrets
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "solace.name" . }}
type: Opaque
data:
  username_admin_password: {{ b64enc "admin" }}