{{- if and .Values.insights.enabled .Values.insights.forwarding.enabled }}
{{- if .Values.insights.forwarding.otelConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "solace.fullname" . }}-otel-config
  labels:
    app.kubernetes.io/name: {{ template "solace.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
stringData:
  otel-config.yaml: |-
{{ .Values.insights.forwarding.otelConfig | indent 4 }}
{{- end }}
{{- end }}
