{{- define "insightsAgent.sempPort" -}}
{{- $portName := ternary "tls-semp" "tcp-semp" .Values.tls.enabled -}}
{{- range .Values.service.ports -}}
  {{- if eq .name $portName -}}
    {{- .containerPort -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "insightsAgent.sempProtocol" -}}
{{- if .Values.tls.enabled -}}
https
{{- else -}}
http
{{- end -}}
{{- end -}}

{{- define "insightsAgent.password" -}}
{{- $secretName := printf "%s-insights-secrets" (include "solace.fullname" .) }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
  {{- index $secret.data "username_insights_password" | b64dec }}
{{- else }}
  {{- randAlpha 10 }}
{{- end }}
{{- end -}}

{{- if .Values.insights.enabled }}
{{- if not .Values.insights.environmentVariables }}
{{- fail "insights.environmentVariables must be defined when Insights is enabled" }}
{{- end }}
{{- if not .Values.insights.environmentVariables.INSIGHTS_AGENT_API_KEY }}
{{- fail "insights.environmentVariables.INSIGHTS_AGENT_API_KEY must be defined when Insights is enabled" }}
{{- end }}
{{- if not .Values.insights.environmentVariables.INSIGHTS_AGENT_SITE }}
{{- fail "insights.environmentVariables.INSIGHTS_AGENT_SITE must be defined when Insights is enabled" }}
{{- end }}
{{- if not .Values.insights.environmentVariables.INSIGHTS_AGENT_TAGS }}
{{- fail "insights.environmentVariables.INSIGHTS_AGENT_TAGS must be defined when Insights is enabled" }}
{{- end }}

{{- $insightsPasswordValue := include "insightsAgent.password" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "solace.fullname" . }}-insights-secrets
  labels:
    app.kubernetes.io/name: {{ template "solace.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  username_insights_password: {{ $insightsPasswordValue | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "solace.fullname" . }}-insights-agent-env-secrets
type: Opaque
data:
  {{- range $key, $value := .Values.insights.environmentVariables }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
stringData:
  INSIGHTS_AGENT_BROKER_HOSTNAME: "localhost"
  INSIGHTS_AGENT_SEMP_USERNAME: "insights"
  INSIGHTS_AGENT_SEMP_PASSWORD: {{ $insightsPasswordValue | quote }}
  INSIGHTS_AGENT_SEMP_PORT: "{{ template "insightsAgent.sempPort" . }}"
  INSIGHTS_AGENT_SEMP_PROTOCOL: {{ template "insightsAgent.sempProtocol" . }}
  INSIGHTS_AGENT_HEALTH_CHECK_PORT: "5550"
{{- end }}
