apiVersion: v1
kind: Secret
metadata:
  name: {{ template "solace.fullname" . }}-secrets
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "solace.name" . }}
type: Opaque
data:
{{/* Require password for HA deployment. For non-HA deployment generate password if not provided */}}
{{- if .Values.solace.redundancy }}
  username_admin_password: {{ required "Setting of solace.usernameAdminPassword value is required!" .Values.solace.usernameAdminPassword | b64enc | quote }}
{{- else }}
  {{ if .Values.solace.usernameAdminPassword }}
  username_admin_password:  {{ .Values.solace.usernameAdminPassword | b64enc | quote }}
  {{ else }}
  username_admin_password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
{{- end }}
