apiVersion: v1
kind: Secret
metadata:
  name: {{ template "solace.fullname" . }}-secrets
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "solace.name" . }}
type: Opaque
data:
{{ if .Values.solace.usernameAdminPassword }}
  username_admin_password:  {{ .Values.solace.usernameAdminPassword | b64enc | quote }}
{{ else }}
  username_admin_password: {{ randAlphaNum 10 | b64enc | quote }}
{{ end }}
