apiVersion: v1
kind: Secret
metadata:
  name: {{ template "solace.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ template "solace.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
{{ if .Values.solace.usernameAdminPassword }}
  username_admin_password:  {{ .Values.solace.usernameAdminPassword | b64enc | quote }}
{{ else }}
  username_admin_password: {{ randAlphaNum 10 | b64enc | quote }}
{{ end }}
