# Load Service part of template
apiVersion: v1
kind: Service
metadata:
  name: {{ template "solace.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "solace.name" . }}
spec:
  type: {{.Values.service.type | default "LoadBalancer"}}
  ports:
  {{- range $item := .Values.service.ports }}
  - port: {{ $item.servicePort }}
    targetPort: {{ $item.containerPort }}
    protocol: {{ $item.protocol }}
    name: {{ $item.name }}
  {{- end}}
  selector:
    app: {{ template "solace.name" . }}
    release: {{ .Release.Name }}
    active: "true"
