apiVersion: v1
kind: Service
metadata:
  name: {{ template "solace.fullname" . }}-discovery
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "solace.name" . }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 8080
      name: semp
  clusterIP: None
  selector:
    app: {{ template "solace.name" . }}
    release: {{ .Release.Name }}