# Load Service part of template
apiVersion: v1
kind: Service
metadata:
  name: {{ template "solace.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "solace.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{.Values.service.type | default "LoadBalancer"}}
  ports:
  {{- range $item := .Values.service.ports }}
  - port: {{ $item.servicePort }}
    targetPort: {{ $item.containerPort }}
    protocol: {{ $item.protocol }}
    name: {{ $item.name }}
  {{- end}}
  selector:
    app.kubernetes.io/name: {{ template "solace.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    active: "true"
