# Create the StatefulSet needed for redundancy
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "solace.fullname" . }}
  labels:
    app: {{ template "solace.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "solace.name" . }}
      release: {{ .Release.Name }}
  serviceName: {{ template "solace.fullname" . }}-discovery
  replicas: {{- if .Values.solace.redundancy }} 3 {{- else }} 1 {{- end }}
  podManagementPolicy: Parallel
  updateStrategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "solace.name" . }}
        release: {{ .Release.Name }}
    spec:
{{- if .Values.image.pullSecretName }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecretName}}
{{- end}}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        resources:
          requests:
{{- if eq .Values.solace.size "dev" }}
            cpu: "0.2"
            memory: 0.8Gi
{{- else if eq .Values.solace.size "prod100" }}
            cpu: "1.2"
            memory: 2Gi
{{- else if eq .Values.solace.size "prod1k" }}
            cpu: "1.2"
            memory: 4Gi
{{- else if eq .Values.solace.size "prod10k" }}
            cpu: "3.5"
            memory: 12Gi
{{- else if eq .Values.solace.size "prod100k" }}
            cpu: "7.5"
            memory: 28Gi
{{- else if eq .Values.solace.size "prod200k" }}
            cpu: "11.5"
            memory: 56Gi
{{- end }}
          limits:
{{- if eq .Values.solace.size "dev" }}
            cpu: "1"
            memory: 2Gi
{{- else if eq .Values.solace.size "prod100" }}
            cpu: "2"
            memory: 3Gi
{{- else if eq .Values.solace.size "prod1k" }}
            cpu: "2"
            memory: 7.5Gi
{{- else if eq .Values.solace.size "prod10k" }}
            cpu: "4"
            memory: 15Gi
{{- else if eq .Values.solace.size "prod100k" }}
            cpu: "8"
            memory: 30Gi
{{- else if eq .Values.solace.size "prod200k" }}
            cpu: "12"
            memory: 60Gi
{{- end }}
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 300
          timeoutSeconds: 5
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          exec:
            command:
            - /mnt/disks/solace/readiness_check.sh
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_NICE
        env:
        - name: STATEFULSET_NAME
          value: {{ template "solace.fullname" . }}
        - name: STATEFULSET_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
         - bash
         - "-ec"
         - |
           source /mnt/disks/solace/init.sh
           # not using postinstall hooks because of order dependencies
           # launch config check then Solace so VCMR can provide return code
           nohup /mnt/disks/solace/config-sync-check.sh &
           /usr/sbin/boot.sh

        volumeMounts:
        - name: config-map
          mountPath: /mnt/disks/solace
        - name: secrets
          mountPath: /mnt/disks/secrets
          readOnly: true
        - name: dshm
          mountPath: /dev/shm
        - name: data
          mountPath: /usr/sw/jail
          subPath: jail
        - name: data
          mountPath: /usr/sw/var
          subPath: var
        - name: data
          mountPath: /usr/sw/internalSpool
          subPath: internalSpool
        - name: data
          mountPath: /usr/sw/adb
          subPath: adb
        - name: data
          mountPath: /var/lib/solace/diags
          subPath: diags
{{- if not .Values.storage.nfs }}
        # only mount when not using nfs
        - name: data
          mountPath: /usr/sw/internalSpool/softAdb
          subPath: softAdb
{{- end }} #end !nfs
        ports:
        {{- range $item := .Values.service.ports }}
        - containerPort: {{ $item.containerPort }}
          protocol: {{ $item.protocol }}
        {{- end}}
      volumes:
        - name: config-map
          configMap:
            name: {{ template "solace.fullname" . }}
            defaultMode: 0755
        - name: secrets
          secret:
            secretName: {{ template "solace.fullname" . }}-secrets
            defaultMode: 0400
        - name: dshm
          emptyDir:
            medium: Memory
{{- if .Values.storage }}
  {{- if not .Values.storage.persistent }}
        - name: data
    {{- if .Values.storage.hostPath }}
          hostPath:
            path: {{ .Values.storage.hostPath }}
    {{- else if .Values.storage.existingVolume }}
      {{- if eq .Values.cloudProvider  "aws" }}
          awsElasticBlockStore:
            volumeID: {{ .Values.storage.existingVolume }}
            fsType: xfs
      {{- else if eq .Values.cloudProvider "gcp" }}
          gcePersistentDisk:
            pdName: {{ .Values.storage.existingVolume }}
            fsType: ext4
      {{- end}}
    {{- else }}
          emptyDir: {}
    {{- end }}
  {{ else }} #end !persistent
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
  {{- if .Values.storage.useStorageClass }}
      storageClassName: {{ .Values.storage.useStorageClass }}
  {{- else if .Values.storage.type }}
      storageClassName: {{ .Release.Name }}-{{ .Values.storage.type }}
  {{- end}}
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage.size}}
  {{- end }}
{{- end}} #end storage
