apiVersion: v1
description: Deploy Solace PubSub+ Event Broker Singleton or HA redundancy group onto a Kubernetes Cluster
name: pubsubplus
version: 2.3.0
icon: https://solaceproducts.github.io/pubsubplus-kubernetes-quickstart/images/PubSubPlus.png
maintainers:
  - name: Solace Community Forum
    url: https://solace.community/
  - name: Solace Support
    url: https://solace.com/support/
home: https://dev.solace.com
sources:
   - https://github.com/SolaceProducts/pubsubplus-kubernetes-quickstart
keywords:
- solace
- pubsubplus
- pubsub+
- pubsub
- messaging
- advanced event broker
- event broker
- event mesh
- event streaming
- data streaming
- event integration
- middleware
