name: Test Helm Templates

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Run Helm Template Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r tests/python/requirements.txt

    - name: Run tests
      run: |
        cd tests/python
        pytest
