name: Test Helm Templates

on:
  push:

jobs:
  test:
    name: Run Helm Template Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r tests/python/requirements.txt

    - name: Run tests
      run: |
        cd tests/python
        pytest
